/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      emerald: colors.emerald,
      indigo: colors.indigo,
      yellow: colors.yellow,
      red: colors.red,
      green: colors.green,
      blue: colors.blue,
      purple: colors.purple,
      pink: colors.pink,
      orange: colors.orange,
      sky: colors.sky,
      teal: colors.teal,
      lime: colors.lime,
      rose: colors.rose,
      fuchsia: colors.fuchsia,
      violet: colors.violet,
      amber: colors.amber,
      lime: colors.lime,
      cyan: colors.cyan,
      rose: colors.rose,
      sky: colors.sky,
      slate: colors.slate,
      zinc: colors.zinc,
      stone: colors.stone,
      neutral: colors.neutral,
      stone: colors.stone,
      warmGray: colors.warmGray,
      trueGray: colors.trueGray,
      coolGray: colors.coolGray,
      blueGray: colors.blueGray,
      coolGray: colors.coolGray,
      primary: "#FF6C5C",
      secondary: "#002D70",
      background: "#050505",
      success: "rgba(39, 206, 164, 1)",
      warning: "rgba(255, 192, 71, 1)",
      danger: "#FF6352",
      cool: "#0062F5",
      strong: "#210B08",
      crimson: "#622018",
      fire: "#AB2F21",
      coral: "#FF9185",
      salmon: "#FFBFB8",
    },
    extend: {},
  },
  plugins: [],
};
