export const blogsList = [
  {
    key: "blockchain_is_shaping_the_future_of_financial_services",
    title: "Blockchain is Shaping the Future of Financial Services",
    shortDes:
      "If you've worked with Next.js, it's likely that you've come across Next Image component. This hassle-free image optimization solution not only provides support for modern formats such as webp and avif but also generates multiple versions tailored to different screen sizes.",
    previewImg: "/images/careers/about.jpg",
    writer: "Author’s name",
    createAt: new Date("04/12/2024"),
    content: `<h2>Lorem ipsum dolor sit amet consectetur. Lobortis</h2>
    <p>Lorem ipsum dolor sit amet consectetur. Nibh ullamcorper feugiat arcu in porttitor integer. Ornare neque diam quis nunc est interdum diam. Netus a adipiscing vivamus lectus. Eu aliquam nisl commodo sed sit fermentum mollis aliquam magna. Nisl nibh risus netus tellus purus mattis risus eget ut. Ultrices dolor ultrices aliquam est facilisis tincidunt mi faucibus cursus. Ultrices tristique magna netus felis nec. At at mauris pharetra tortor aliquam. Condimentum pellentesque turpis urna proin. Neque interdum cursus fermentum risus bibendum condimentum. Urna libero turpis pellentesque convallis.<br />Eleifend consequat massa magna vehicula aliquam. Dui euismod in sed velit sagittis. Tristique turpis tortor purus velit varius accumsan tempor erat dignissim. Pellentesque purus tellus id neque sollicitudin. Viverra velit mattis semper et. Est duis libero dignissim elementum. Non enim est sagittis ac. Eget volutpat sit nec egestas aliquet. In eget amet nisi lectus fermentum arcu ornare. Suscipit curabitur sapien suspendisse tellus netus magna nibh turpis.<br />Gravida diam semper faucibus iaculis tortor in tincidunt. Velit risus convallis risus in consectetur feugiat eu auctor feugiat. Mi eros odio nulla senectus. Lorem massa viverra fames nisi pellentesque commodo lectus est. A.</p>
    <p><img src="https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w600/2023/10/free-images.jpg" alt="" width="1000" height="666" /></p>
    <h2>Lorem ipsum dolor sit amet consectetur. Lobortis</h2>
    <p>Lorem ipsum dolor sit amet consectetur. Nibh ullamcorper feugiat arcu in porttitor integer. Ornare neque diam quis nunc est interdum diam. Netus a adipiscing vivamus lectus. Eu aliquam nisl commodo sed sit fermentum mollis aliquam magna. Nisl nibh risus netus tellus purus mattis risus eget ut. Ultrices dolor ultrices aliquam est facilisis tincidunt mi faucibus cursus. Ultrices tristique magna netus felis nec. At at mauris pharetra tortor aliquam. Condimentum pellentesque turpis urna proin. Neque interdum cursus fermentum risus bibendum condimentum. Urna libero turpis pellentesque convallis.<br />Eleifend consequat massa magna vehicula aliquam. Dui euismod in sed velit sagittis. Tristique turpis tortor purus velit varius accumsan tempor erat dignissim. Pellentesque purus tellus id neque sollicitudin. Viverra velit mattis semper et. Est duis libero dignissim elementum. Non enim est sagittis ac. Eget volutpat sit nec egestas aliquet. In eget amet nisi lectus fermentum arcu ornare. Suscipit curabitur sapien suspendisse tellus netus magna nibh turpis.<br />Gravida diam semper faucibus iaculis tortor in tincidunt. Velit risus convallis risus in consectetur feugiat eu auctor feugiat. Mi eros odio nulla senectus. Lorem massa viverra fames nisi pellentesque commodo lectus est. A.</p>
    <p><img src="https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w600/2023/10/free-images.jpg" alt="" width="1000" height="666" /></p>`,
  },
  {
    key: "how_ai_is_transforming_business_operations_in_2024",
    title: "How AI is Transforming Business Operations in 2024?",
    shortDes:
      "If you've worked with Next.js, it's likely that you've come across Next Image component. This hassle-free image optimization solution not only provides support for modern formats such as webp and avif but also generates multiple versions tailored to different screen sizes.",
    previewImg: "/images/careers/about.jpg",
    writer: "Author’s name",
    createAt: new Date("04/2/2024"),
    content: `<h2>Lorem ipsum dolor sit amet consectetur. Lobortis</h2>
    <p>Lorem ipsum dolor sit amet consectetur. Nibh ullamcorper feugiat arcu in porttitor integer. Ornare neque diam quis nunc est interdum diam. Netus a adipiscing vivamus lectus. Eu aliquam nisl commodo sed sit fermentum mollis aliquam magna. Nisl nibh risus netus tellus purus mattis risus eget ut. Ultrices dolor ultrices aliquam est facilisis tincidunt mi faucibus cursus. Ultrices tristique magna netus felis nec. At at mauris pharetra tortor aliquam. Condimentum pellentesque turpis urna proin. Neque interdum cursus fermentum risus bibendum condimentum. Urna libero turpis pellentesque convallis.<br />Eleifend consequat massa magna vehicula aliquam. Dui euismod in sed velit sagittis. Tristique turpis tortor purus velit varius accumsan tempor erat dignissim. Pellentesque purus tellus id neque sollicitudin. Viverra velit mattis semper et. Est duis libero dignissim elementum. Non enim est sagittis ac. Eget volutpat sit nec egestas aliquet. In eget amet nisi lectus fermentum arcu ornare. Suscipit curabitur sapien suspendisse tellus netus magna nibh turpis.<br />Gravida diam semper faucibus iaculis tortor in tincidunt. Velit risus convallis risus in consectetur feugiat eu auctor feugiat. Mi eros odio nulla senectus. Lorem massa viverra fames nisi pellentesque commodo lectus est. A.</p>
    <p><img src="https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w600/2023/10/free-images.jpg" alt="" width="1000" height="666" /></p>
    <h2>Lorem ipsum dolor sit amet consectetur. Lobortis</h2>
    <p>Lorem ipsum dolor sit amet consectetur. Nibh ullamcorper feugiat arcu in porttitor integer. Ornare neque diam quis nunc est interdum diam. Netus a adipiscing vivamus lectus. Eu aliquam nisl commodo sed sit fermentum mollis aliquam magna. Nisl nibh risus netus tellus purus mattis risus eget ut. Ultrices dolor ultrices aliquam est facilisis tincidunt mi faucibus cursus. Ultrices tristique magna netus felis nec. At at mauris pharetra tortor aliquam. Condimentum pellentesque turpis urna proin. Neque interdum cursus fermentum risus bibendum condimentum. Urna libero turpis pellentesque convallis.<br />Eleifend consequat massa magna vehicula aliquam. Dui euismod in sed velit sagittis. Tristique turpis tortor purus velit varius accumsan tempor erat dignissim. Pellentesque purus tellus id neque sollicitudin. Viverra velit mattis semper et. Est duis libero dignissim elementum. Non enim est sagittis ac. Eget volutpat sit nec egestas aliquet. In eget amet nisi lectus fermentum arcu ornare. Suscipit curabitur sapien suspendisse tellus netus magna nibh turpis.<br />Gravida diam semper faucibus iaculis tortor in tincidunt. Velit risus convallis risus in consectetur feugiat eu auctor feugiat. Mi eros odio nulla senectus. Lorem massa viverra fames nisi pellentesque commodo lectus est. A.</p>
    <p><img src="https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w600/2023/10/free-images.jpg" alt="" width="1000" height="666" /></p>`,
  },
  {
    key: "best_practices_for_remote_software_development_team",
    title: "Best Practices for Remote Software Development Team",
    shortDes:
      "If you've worked with Next.js, it's likely that you've come across Next Image component. This hassle-free image optimization solution not only provides support for modern formats such as webp and avif but also generates multiple versions tailored to different screen sizes.",
    previewImg: "/images/careers/about.jpg",
    writer: "Author’s name",
    createAt: new Date("08/20/2024"),
    content: `<h2>Lorem ipsum dolor sit amet consectetur. Lobortis</h2>
    <p>Lorem ipsum dolor sit amet consectetur. Nibh ullamcorper feugiat arcu in porttitor integer. Ornare neque diam quis nunc est interdum diam. Netus a adipiscing vivamus lectus. Eu aliquam nisl commodo sed sit fermentum mollis aliquam magna. Nisl nibh risus netus tellus purus mattis risus eget ut. Ultrices dolor ultrices aliquam est facilisis tincidunt mi faucibus cursus. Ultrices tristique magna netus felis nec. At at mauris pharetra tortor aliquam. Condimentum pellentesque turpis urna proin. Neque interdum cursus fermentum risus bibendum condimentum. Urna libero turpis pellentesque convallis.<br />Eleifend consequat massa magna vehicula aliquam. Dui euismod in sed velit sagittis. Tristique turpis tortor purus velit varius accumsan tempor erat dignissim. Pellentesque purus tellus id neque sollicitudin. Viverra velit mattis semper et. Est duis libero dignissim elementum. Non enim est sagittis ac. Eget volutpat sit nec egestas aliquet. In eget amet nisi lectus fermentum arcu ornare. Suscipit curabitur sapien suspendisse tellus netus magna nibh turpis.<br />Gravida diam semper faucibus iaculis tortor in tincidunt. Velit risus convallis risus in consectetur feugiat eu auctor feugiat. Mi eros odio nulla senectus. Lorem massa viverra fames nisi pellentesque commodo lectus est. A.</p>
    <p><img src="https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w600/2023/10/free-images.jpg" alt="" width="1000" height="666" /></p>
    <h2>Lorem ipsum dolor sit amet consectetur. Lobortis</h2>
    <p>Lorem ipsum dolor sit amet consectetur. Nibh ullamcorper feugiat arcu in porttitor integer. Ornare neque diam quis nunc est interdum diam. Netus a adipiscing vivamus lectus. Eu aliquam nisl commodo sed sit fermentum mollis aliquam magna. Nisl nibh risus netus tellus purus mattis risus eget ut. Ultrices dolor ultrices aliquam est facilisis tincidunt mi faucibus cursus. Ultrices tristique magna netus felis nec. At at mauris pharetra tortor aliquam. Condimentum pellentesque turpis urna proin. Neque interdum cursus fermentum risus bibendum condimentum. Urna libero turpis pellentesque convallis.<br />Eleifend consequat massa magna vehicula aliquam. Dui euismod in sed velit sagittis. Tristique turpis tortor purus velit varius accumsan tempor erat dignissim. Pellentesque purus tellus id neque sollicitudin. Viverra velit mattis semper et. Est duis libero dignissim elementum. Non enim est sagittis ac. Eget volutpat sit nec egestas aliquet. In eget amet nisi lectus fermentum arcu ornare. Suscipit curabitur sapien suspendisse tellus netus magna nibh turpis.<br />Gravida diam semper faucibus iaculis tortor in tincidunt. Velit risus convallis risus in consectetur feugiat eu auctor feugiat. Mi eros odio nulla senectus. Lorem massa viverra fames nisi pellentesque commodo lectus est. A.</p>
    <p><img src="https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w600/2023/10/free-images.jpg" alt="" width="1000" height="666" /></p>`,
  },
];
